[workspace]
resolver = "3"
members = ["crates/tallow-core", "crates/tallow-tui"]
default-members = ["crates/tallow-tui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
tallow-core = { path = "crates/tallow-core" }
ratatui = "0.30"
rand = { version = "0.10", default-features = false, features = ["alloc"] }
rand_pcg = { version = "0.10", default-features = false }
serde = { version = "1", features = ["derive"] }
ron = "0.12"
slotmap = "1"
anyhow = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
